[package]
name = "picana_native"
version = "0.1.0"
authors = ["Harry K <kituyiharry@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "picana"
crate-type = ["dylib"]

[dependencies]
memmap = "0.7.0"
lazy_static = "1.4.0"
libc = "0.2"
hex = "0.2.0"
canparse =  "0.1.4"
socketcan = { path = '../socketcan-rs' }

# Replace current nix version!(socketcan use 0.5.1 which isn't android compatible)
[replace]
"nix:0.5.1" = { path = '../nix' }
