name: picana_dart
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  ffi: ^0.1.3
  rxdart: ^0.23.1

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
