name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Prepare
      run: git submodule update --init
    - name: Build
      run: cd ./picana_native && cargo build --verbose
    - name: Run tests
      run: cd ./picana_native && cargo test --verbose
