name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Prepare
      run:  git submodule update --init
    - name: Patch SocketCan
      run:  cd ./socketcan-rs && git apply ../socketcan_libc.diff
    - name: Patch nix
      run:  cd ./nix && git apply ../nix_patch.diff
    - name: Build
      run:  cd ./picana_native && cargo build --verbose
    - name: Run tests
      run:  cd ./picana_native && cargo test --verbose
